### ISSUE TITLE
(REQUEST) support conda or pip install 

### ISSUE THREAD

**Issue by WangLiwen1994** [BrokenSource/DepthFlow#14]
Hello,
Very nice tool, would it be possible to support conda/pip installation?

**Comment by Tremeschin** [comment]
I don't really plan on conda, but there's a PyPI package with all projects already :) 

https://pypi.org/project/broken-source

https://brokensrc.dev/get/pypi

PyTorch isn't included in the dependencies, install one version in the venv / add to `pyproject.toml` at

https://pytorch.org/get-started/locally

From there, you can just type `depthflow` or other projects' names as they are also installed as modules entry point scripts

I haven't tried myself, but you can `from DepthFlow.DepthFlow import DepthFlowScene` alongside some/most of this file imports of ShaderFlow and-

-there's an example at the bottom of `DepthFlow.py` on how to do inheritance and writing your own class

lmk if this works!

Wheels are a bit experimental but I've got success so far

**Comment by Tremeschin** [comment]
I'm closing as it's been a while, and a [PyPI](https://pypi.org/project/broken-source/) wheel exists! :)

I'll upload soon a version 0.2.0 with some important fixes of the latest commits, I know it's outdated

Conda is on plans™, I've used miniconda to run some other project and I didn't dislike it 👍🏻
