### ISSUE TITLE
(REQUEST) A way of executing this without launchin UI

### ISSUE THREAD

**Issue by hucara** [BrokenSource/DepthFlow#19]
Is it planned to add a CLI only mode to this? This would be nice to have.

**Comment by suraj-avataar** [comment]
Was a CLI only version provided?

**Comment by Tremeschin** [comment]
hm, I missed this issue

if you mean "UI" as the real time window, sure, just use `WINDOW_BACKEND=headless` (or initialize a Scene with `Scene(backend="headless)`), no real time window will pop up (docker files works like this as well)

CLI always has been the focus of everything, and when exporting to a video it keeps the glfw window hidden, or better yet use the headless context

**Comment by suraj-avataar** [comment]
Thanks, that helped
