### ISSUE TITLE
(BUG) GLIBC not found when executing new PyApp release on linux

### ISSUE THREAD

**Issue by hucara** [BrokenSource/DepthFlow#23]
I'm trying the newly packaged release and having problems with GLIBC not found. Currently I am unable to upgrade the operating system:

```
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
```

This happens with all linux executables: CUDA, CPU and Rocm. 
Is there a better way to run this in headless mode from command line and that does not require GLIBC? Other installation ways are quite convoluted and depend on RYE or the BrokenSource itself.

The exact errors are:

```
./depthflow-cpu-linux-amd64-0.3.1.bin: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./depthflow-cpu-linux-amd64-0.3.1.bin)
./depthflow-cpu-linux-amd64-0.3.1.bin: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./depthflow-cpu-linux-amd64-0.3.1.bin)
./depthflow-cpu-linux-amd64-0.3.1.bin: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./depthflow-cpu-linux-amd64-0.3.1.bin)
```

And the command executed was:
`./depthflow-rocm-linux-amd64-0.3.1.bin input -i ./blabla.png main -q 90 -s 2 -o ./video.mp4
`

**Comment by Tremeschin** [comment]
Hi, just a heads up, I have recently set up CI with GitHub Actions, and I'm able to set the oldest (supported) Linux system to ubuntu-20.04, which I'll release version v0.5.0 within a week™, and will have a lower GLIBC requirement

If that still isn't 'old enough', I can try setting up releases through older images with Docker, but I'd prefer otherwise 😅

**Comment by Tremeschin** [comment]
Hi², I've pushed a new 0.5.0 release that was built on ubuntu 20.04 on gh actions, could you test it if you're still interested?

**Comment by Tremeschin** [comment]
Just followed this [stackoverflow](https://stackoverflow.com/a/3436360) answer for finding out the minimum glibc for a binary,

```
# Version at when the issue was created
❯ objdump -T ./depthflow-cpu-linux-amd64-0.3.1.bin | grep GLIBC | sed 's/.*GLIBC_\([.0-9]*\).*/\1/g' | sort -Vu
(...)
2.33
2.34

# New release with Actions CI made on Ubuntu 20.04
❯ objdump -T ./depthflow-cpu-linux-amd64-0.5.0.bin | grep GLIBC | sed 's/.*GLIBC_\([.0-9]*\).*/\1/g' | sort -Vu      
(...)
2.28
2.29
```

So, minimum glibc version has went down from 2.34 to 2.29, which should be enough for Debian 11 given a quick research showed me the `oldstable` branch is at 2.31. Feel free to reopen if it's still an issue!
