### ISSUE TITLE
Deal with settings for simple movement ?

### ISSUE THREAD

**Issue by ti2** [BrokenSource/DepthFlow#24]
Hi, for last day, i have been looking for the perfect settings to create a simple horizontal camera movement. 
Here is what I tried, without success:
depthflow-latest.exe input -i image.jpg -d depth.png main -t 4 -s 2 -ofx 10 -o video.mp4

Thanks in advance for any help, and thanks for this amazing script.
best regards, Peter

**Comment by Tremeschin** [comment]
Hey! It's currently not possible to change the animation on binary releases (I also gotta update them)

For that I'd suggest running  [from source](https://brokensrc.dev/get/source/) and manually edit [this function](https://github.com/BrokenSource/DepthFlow/blob/9146606b80fb4e465e47fc1d639e00cb835f6513/DepthFlow/DepthScene.py#L300) to something like:

```python
def update(self):
    self.state.offset_x = math.sin(2*self.cycle)
    return
```

I will code a preset system next, as I understood a nice pattern to integrate with the CLI, should be there within a week

**Comment by Tremeschin** [comment]
Well, technically, you can find that file on the executable you're using on `%applocaldata%\pyapp\*\site-packages\DepthFlow\DepthFlow.py` and change the same function's animation code :)

**Comment by Tremeschin** [comment]
In case you want a more "linear" horizontal movement instead of that smooth one with `sin(x)`,
```python
def update(self):
    self.state.offset_x = 1 - 1.2*math.acos(math.sin(2*self.cycle))*(2/math.pi)
    return
```

Feel free to also add some lines configuring other options like making the background stationary

```python
def update(self):
    self.state.offset_x = 1 - 1.2*math.acos(math.sin(2*self.cycle))*(2/math.pi)
    self.state.focus = 0 # There's a big class on the start of the file saying what parameters do
    return
```

If running from newest versions from source, you can run `depthflow config` to see and set those options to a fixed value

There's also a depth of field and vignette effects that can be enabled, there's examples on `depthflow` command help

**Comment by Tremeschin** [comment]
Example with the last message's `.update` and the following command (won't work on .exe until the v0.4.0`:

- `depthflow dof -e vignette -e config --static 0 main -o ~/depth.mp4`

https://github.com/BrokenSource/DepthFlow/assets/29046864/4524b765-bf56-4c5f-a538-4b83b2251d16

**Comment by ti2** [comment]
Thank you so much! After a bit of tweaking, your solution work like a charm.
