### ISSUE TITLE
(REQUEST) Ability to dump frames instead of a video

### ISSUE THREAD

**Issue by agoralski** [BrokenSource/DepthFlow#26]
Would it be possible to dump frames to individual files instead of a video container?

**Comment by Tremeschin** [comment]
You can technically inherit your own class [like here](https://github.com/BrokenSource/DepthFlow/blob/52e73414d4d54adaf1145efcdecee6ace727fc7f/Custom.py#L12) or on the DepthScene class's `.update` method, and use:

```python
def update(self):
    frame = self.read_screen()
    image = PIL.Image.frombytes("RGB", self.resolution, frame)
    image = image.transpose(PIL.Image.FLIP_TOP_BOTTOM)
```

Similar mechanism for [taking screenshots](https://github.com/BrokenSource/ShaderFlow/blob/fd72f6d17d2c2a6b47b369a060e92a01a9392dae/ShaderFlow/Scene.py#L879) on shaderflow !

If you want a numpy array which will be faster than using PIL Image, something like the following could work:

`numpy.frombuffer(frame, dtype=numpy.uint8).reshape((*self.resolution, -1))`

**Comment by agoralski** [comment]
Awesome, thanks for your help! I don't need the frames to be sent to ffmpeg in my case.

Using depthflow to generate different views on the object for training a model for object recognition. It helps me build a larger image dataset from slightly different views :)

**Comment by Tremeschin** [comment]
Oh, interesting, yea, that way I've talked about should do it for your case, set random or custom/known parameters on a .update, grab the screen contents, move on infinitely until you reach a certain `self.frame` or `self.time` !

Be sure to use DepthAnythingV2 on the `self.estimator` property! it's much better :)

**Comment by Tremeschin** [comment]
Just adding to your use case, maybe a headless window can go handy for you with `WINDOW_BACKEND=headless` or initializing your inherited class with `YourScene(backend="headless")`, so there's not a chance to mess up window resizes / be limited by the monitor size
