### ISSUE TITLE
Animations on the WebUI aren't configurable as on the CLI

### ISSUE THREAD

**Issue by onlysharma0852** [BrokenSource/DepthFlow#35]
Thanks for making the web UI. I was only waiting for this. Everything is  working fine. Only one thing is missing is that different video art style. In current state only perspective video style is available. If you can add other style also like circular, horizontal, vertical, zoom in and out, dolly than it will be perfect. i think this is the only thing that is missing. Otherwise everything is really good and thanks for making a perfect alternative of that expensive immersityAI .

**Comment by Tremeschin** [comment]
yup, configuring the animations are missing on the webui, and it's understandable waiting for it 😅 

I took a short code break, getting back to it, will review the animation system that currently exists on CLI on v0.6.0 or git main, and integrate it with the webui as the next _big_ feature

subject to changes, but what you described is possible on cli:
- `depthflow circle input -i image.png main (...)`
- `depthflow zoom --loop main (...)`
- also `horizontal, vertical`, see their `--help` or just `depthflow circle` for parameters

won't be an easy task dynamically creating the webui, but certainly the gradio api for it won't look pretty haha

**Comment by Tremeschin** [comment]
Just pushed a webui rewrite in https://github.com/BrokenSource/DepthFlow/commit/e7d7058bc1ed1fd71372d9c972fbfae5bca3fea7 with an initial integration with the preset systems!

![image](https://github.com/user-attachments/assets/c27c07fe-87cb-46b0-a2a4-3eb19ec97eca)

currently only available if running directly from [source code](https://brokensrc.dev/get/source/), will be part of a pypi and binary v0.7 release (soon?), run it with `depthflow-gradio` with the python venv activated (needs `rye sync` if updating `git pull --recurse-submodules`)

surely there will be some rough edges, bugs, and room for improvement (the animations layout, explaining parameters just isn't there), those will come as it matures; the rewrite of the preset system will definitely help

<sup>I'll keep the issue open until the v0.7 is released</sup>

**Comment by Tremeschin** [comment]
Just hit release v0.7.0 milestone!
- https://github.com/BrokenSource/DepthFlow/releases/tag/v0.7.0
- https://pypi.org/project/depthflow/

Feedback appreciated! 🙂

Any issues that might pop will follow a v0.7.1 shortly after

**Comment by onlysharma0852** [comment]
Thank you so much.❤️
