### ISSUE TITLE
dolly -r for reverse seems to have no effect

### ISSUE THREAD

**Issue by mnlkrp** [BrokenSource/DepthFlow#37]
### 🔘 Operating system

Windows 10

### 🔘 Runtime enviroment

PyPI Wheels (pip, poetry, pdm, rye, etc)

### 🔘 Python version

Python 3.12

### 🔘 GPU Vendor

NVIDIA Desktop

### 🔘 Description

dolly -r for reverse seems to have no effect. tested with different settings, just putting in the picture + "dolly -r main" but it doesn't reverse the playback.

**Comment by Tremeschin** [comment]
thanks for the report,

I'll soon revisit the animation system as a whole, as it's the first iteration of it I've written a few weeks ago, I'm not surprised there's some edge cases and inconsistencies across the board, and I know there's other random stuff like bad frames on it (zero divisions)

**Comment by mnlkrp** [comment]
Thank you very much! I'm looking forward to it :)

**Comment by Tremeschin** [comment]
Took a quick look on this one as well, the code is indeed *reversing* the time, or so it thinks.. the problem happens on the phase of the wave, uhm, sorta.. let me explain

<br>

See [this desmos graph](https://www.desmos.com/calculator/udmjokv0ua), the blue line is the starting point, the red is the end point of the isometric effect, the wave inside can either be a sine (default) or triangle, but the idea is the same (being periodic and symmetric)

- with `phi=0`, see how going 'forward' (left to right) we go up first, then down; and when going from right to left (reverse), we go down first, then up

- now, change `phi=0.25` on the slider, you'll see that both  directions gives the same shape function 🤯

that is something so obvious I've never seen on my whole electrical engineering course LOL

<br>

We could start the video mid-way through (I think immersity does this) - maybe even to avoid this same problem -, would you expect it to start all zoomed out or in, or it's ok if it's a perfect loop but starting at the middle of the animation?

<sup>(asking for the animation system v2.0, as this evidently will be a problem</sup>

**Comment by mnlkrp** [comment]
> We could start the video mid-way through (I think immersity does this) - maybe even to avoid this same problem -, would you expect it to start all zoomed out or in, or it's ok if it's a perfect loop but starting at the middle of the animation?

I think starting in the middle of the loop would be my expected behaviour :)

**Comment by Tremeschin** [comment]
Just made the change, it now starts at the middle of the thing with a 'zoom forward', and reverse makes it to 'zoom backwards' at the start

**Comment by Tremeschin** [comment]
Should be fixed on v0.7.0, dolly now starts at the middle of the animation!
- https://github.com/BrokenSource/DepthFlow/releases/tag/v0.7.0
- https://pypi.org/project/depthflow/

Feedback appreciated! 🙂
