### ISSUE TITLE
Single brown frames when exporting into mp4 with standard settings

### ISSUE THREAD

**Issue by mnlkrp** [BrokenSource/DepthFlow#38]
### 🔘 Operating system

Windows 10

### 🔘 Runtime enviroment

PyPI Wheels (pip, poetry, pdm, rye, etc)

### 🔘 Python version

Python 3.12

### 🔘 GPU Vendor

NVIDIA Desktop

### 🔘 Description

Single brown frames when exporting into mp4 with standard settings. About 3 in 10second exports. "-h" settings for height make no difference. "--time"  setting for time makes no difference. There are always 3 brown frames in the export.

│DepthFlow├┤0'21.456├┤INFO   │ ▸ • Stats: (Took 1.42s) at (636.03fps | 10.60x Realtime) with (900 Total Frames)
❯ input -i "xxx\x.png" dolly -d 0.9 main -h 5440 --time 15 -o "xxx\o.mp4"
│DepthFlow├┤1'05.324├┤INFO   │ ▸ OpenGL Renderer: NVIDIA GeForce RTX 2070/PCIe/SSE2
│DepthFlow├┤1'06.267├┤INFO   │ ▸ (51) ShaderObject       │ ▸ Compiling shaders
│DepthFlow├┤1'06.273├┤INFO   │ ▸ (53) ShaderObject       │ ▸ Compiling shaders
│DepthFlow├┤1'06.322├┤INFO   │ ▸ (39) DepthScene         │ ▸ Resized Window to (3072, 5440)
│DepthFlow├┤1'06.334├┤INFO   │ ▸ Running Command ('C:\\Users\\xxx\\AppData\\Local\\BrokenSource\\Broken\\Externals\\Archives\\ffmpeg-master-latest-win64-gpl\\ffmpeg-master-latest-win64-gpl\\bin\\ffmpeg.EXE', '-threads', '0', '-hide_banner', '-loglevel', 'error', '-f', 'rawvideo', '-s', '3072x5440', '-pix_fmt', 'rgb24', '-r', '60.0', '-i', '-', '-c:a', 'copy', '-c:v', 'libx264', '-preset', 'slow', '-crf', '20', '-movflags', '+faststart', '-vf', 'scale=3072:5440:flags=lanczos', '-pix_fmt', 'yuv420p', 'xxx\o.mp4', '-y', '-t', '15.0') @ (xxx)
│DepthFlow├┤2'52.750├┤INFO   │ ▸ Waiting for FFmpeg process to finish (Queued writes, codecs lookahead, buffers, etc)
│DepthFlow├┤3'03.264├┤INFO   │ ▸ Finished rendering (xxx\o.mp4)
│DepthFlow├┤3'03.266├┤INFO   │ ▸ • Stats: (Took 116.92s) at (7.70fps | 0.13x Realtime) with (900 Total Frames)

![image](https://github.com/user-attachments/assets/8cd00446-4472-41e7-91a6-5b3f3d1511ef)

**Comment by Tremeschin** [comment]
oh hi again, related to [#37](https://github.com/BrokenSource/DepthFlow/issues/37#issuecomment-2342146606), just have acknowledged this issue on the other post 😅

**Comment by mnlkrp** [comment]
Yep, just wanted to come here to say it seems to be related to the dolly effect because without it, it renders perfectly fine :)

**Comment by mnlkrp** [comment]
> adding +0.0001 to time fixes it
thanks for the workaround :)

**Comment by Tremeschin** [comment]
I'm taking a look at this actually, should be easily fixable, I know it's something to do when the camera's isometric is _exactly_ 1, like, for real, one (1), I've some new ideas

**Comment by Tremeschin** [comment]
Ok, so this was an interesting one, see the commit https://github.com/BrokenSource/DepthFlow/commit/12917512f7bd187356f8fcaabe20bac296c56ca6

when isometric=1, all rays are parallel from the camera to the scene, and [the angle they intersect is zero](https://github.com/BrokenSource/DepthFlow/blob/12917512f7bd187356f8fcaabe20bac296c56ca6/DepthFlow/Resources/Shaders/DepthFlow.glsl#L43); as 1/tan(angle) is used on the core loop for getting the distance a ray is 'away' from the scene, that's the zero division right there haha

you'll want to run the projects [directly from source](https://brokensrc.dev/get/source/) for this fix

**Comment by mnlkrp** [comment]
> you'll want to run the projects [directly from source](https://brokensrc.dev/get/source/) for this fix, lmk if it's good now !

it worked perfectly fine. it now renders without errors. 

thank you very much!!
