### ISSUE TITLE
DepthFlow cannot be deployed and run

### ISSUE THREAD

**Issue by axtkong** [BrokenSource/DepthFlow#4]
I’m trying to use the DepthFlow project, but it depends on ShaderFlow. After copying ShaderFlow into the projects, I found it depends on Brokens. However, I couldn’t find Brokens under https://github.com/BrokenSource. The entire project cannot run properly. Also, I would like to ask if there is a complete plan for using DepthFlow?

**Comment by Tremeschin** [comment]
Hey, nice catch!

I've some uncommitted changes that fix this

I was playing with ways to integrate the projects with others, plus my private infrastructure, I may have had a few leftovers that work locally only

(I wasn't comfortable with it requiring admin permission for the shared path, which seems to be the error you're having. Maybe  `broken install` didn't run properly?)

Give me a few hours, and I'll make the deployment instructions clearer

**Comment by Tremeschin** [comment]
I've changed and fixed enough parts of the deployment process since the issue was created, and have successfully ran on Windows and Linux with full functionality

I'm temporarily closing this issue, feel free to still give feedback here!
