### ISSUE TITLE
Generated video is whole black

### ISSUE THREAD

**Issue by Balthazariy** [BrokenSource/DepthFlow#41]
### 🔘 Operating system

Windows 10

### 🔘 Runtime enviroment

PyAPP Executables (experimental)

### 🔘 Python version

Python 3.12

### 🔘 GPU Vendor

NVIDIA Laptop

### 🔘 Description

I'm downloaded "depthflow-cuda-windows-amd64-latest.exe" file and run it with cmd.exe from folder "C:\depthflow". With line "depthflow input -i ./0005.jpg main" and in this case i got expected result - animated 2.5d video 
![mKCsQPILRA](https://github.com/user-attachments/assets/80bbb0ef-af6a-474a-9c4b-6b214f7390fc). But when i try to export the result i got black video 10 sec length with next line "depthflow input -i C:\depthflow\0005.jpg main -o C:\depthflow\video.mp4"
![QQVR9ExFSd](https://github.com/user-attachments/assets/791443ab-0599-4be5-b434-29175c5346ad)

What i wrong do?

**Comment by Tremeschin** [comment]
I don't see anything wrong at first glance, and IIRC using a hidden GLFW window for rendering on windows worked fine (at least for nvidia)

I can think of 3 things we can try:

1. as you're on a dedicated gpu and it used the integrated one, try going into the NVIDIA control panel page below, select the "pyapp\something\python.exe" on recents and switch to the proper GPU:

<sub>I didn't run depthflow itself at the time and don't have a hybrid system so the options you'll want to change don't show for me</sub>

![image](https://github.com/user-attachments/assets/83e04c49-187b-40a4-b757-704e2283d101)

2. check the arguments of `depthflow main --help` and add a `--no-turbo` if it exists, the thing [I wrote](https://github.com/BrokenSource/TurboPipe) seems stable everywhere and heavily boosts performance for non-iGPU systems, but it's good to check

3. run `$env:WINDOW_BACKEND="headless"` before the export command, let's see if it's some platform specific with the glfw window maybe failing pixel ownership test (specific to intel if (1) doesn't work)?

<sub>^ that's a powershell command, for cmd it might be `set WINDOW_BACKEND=headless`</sub>

<br>

Let me know if any of these works!

**Comment by Balthazariy** [comment]
Hello again :D
In NVIDIA control panel i set for python.exe my high perfomance GPU - GTX1050Ti and then add -no-turbo. And after this steps all works perfectly!
![j0BWc9ppsv](https://github.com/user-attachments/assets/53d255b5-77a8-48c7-a945-c1b21235a3ba)

**Comment by Balthazariy** [comment]
Thank you for quick answer and this powerfull tool <3

**Comment by Tremeschin** [comment]
<sub>I would have answered faster but I was sleeping 🙂</sub>

I'm happy it's solved, but I wonder why turbopipe failed for you 😅, good thing I made it opt-out haha, it's used on exporting videos only btw

<br>

Unrelated, but on v0.7.0 or current git main it's possible to use like `depthflow input -i ./image.jpg h264-nvenc main -o ./video.mp4` to use the GPU for encoding and changing the encoding parameters, as you're probably CPU limited there on those export speeds :)
