### ISSUE TITLE
No Requirements.txt

### ISSUE THREAD

**Issue by sonicviz** [BrokenSource/DepthFlow#46]
### 🔘 Request type

General feedback

### 🔘 Description

It looks like a very cool project, but it's missing a couple of things for "standard" use. 

eg: 
There's no requirements.txt to set the needed packages if you want to run manually. 
Also, it forces use of rye as a package manager, instead of making this optional. 
Basic standard is just default to regular .venv install system, not require people to install yet another package manager they don't want/need. 

When you're evaluating many packages/projects any extra requirements beyond a "standard" install routine impose a friction that may well impede the adoption of your package. 

I'd provide a default install method based around bog standard requirements.txt + VSCode .venv, then offer the rye method as an optional enhancement. 

Thanks.

**Comment by Tremeschin** [comment]
hi!, here's some comments and insights:

<br>

> Also, it forces use of rye as a package manager

I recognize the _"vendor locking"_ issue with rye, but there's no other python tooling that made a monorepo structure integrate nicely with and managing python, solving the problem quite beautifully with its workspaces features

I can't put into words how flexible this structure is, things are mainly split for issue tracking and visibility though 👀 

this is also only a problem for running directly from source, as [pypi wheels](https://pypi.org/project/depthflow/) exists, realistically speaking :)

<br>

> There's no requirements.txt to set the needed packages if you want to run manually.

I'm not sure if a requirements.txt would be practical or possible, as the main library and shaderflow would need to be set as path dependencies (other repos), getting back to square one of the problem rye solves 😅 

It's possible to [uncomment](https://github.com/BrokenSource/BrokenSource/blob/78bed00d1eb0626b64c9ec5074ced152b16309cf/pyproject.toml#L152) these and `pip install .[all]` without rye at all on the main repo, as pip will also look for `pyproject.toml` first than a `requirements.txt`!

<sup><b>Note:</b> we could specify a stable pypi release of those, but it might break on any mid cycle git main commits, perhaps a "development" branch everywhere?</sup>

it could theoretically be done by listing `git+` dependencies of the dependents repos, but again, there's no PEP for what poetry and rye calls `dev-dependencies` to differentiate regular package dependencies

<hr>

I could write a lot more on this, but ultimately, I prefer users to simply use the pypi wheels and consider running directly from source a developent mode only thing!

**Comment by sonicviz** [comment]
Thanks for the quick reply. 

All good. I'll just go with pip install for now. 

Thanks! Nice work.

**Comment by sonicviz** [comment]
Quick question: Example batch command dolly --intensity 0.5 returns error 
Dolly : The term 'Dolly' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is 
correct and try again.

Is that still under development?

Thanks!

**Comment by Tremeschin** [comment]
Thanks for your understanding!

a, this batch script I didn't test it, one person asked for it yesterday, and it seemed to work, but they might have modified it

It's probably missing \ on the command line endings to chain the three lines together as a single command!

Ideally, the batch exporting logic should be built-in when the input is a folder, I'll check the feasibility :eyes:

<hr>

as for docs/examples, yup, I was just writing it this week and haven't updated with the new stuff, and there definitely will be a section for the animation system and wayy more examples on how to do stuff

**Comment by Tremeschin** [comment]
Ok, tested the batch.ps1 myself and improved it a little, was indeed the lack of a `\` at the end, or rather the ` symbol powershell uses instead of backslash

**Comment by sonicviz** [comment]
kk, So I can update via pip?

Q:
│DepthFlow├┤1'57.568├┤INFO   │ ▸ (Module 77 • YourScene   ) • Stats: (Took 6.24s) at (22.12fps | 0.74x Realtime) with (138 Total Frames)
│DepthFlow├┤1'58.532├┤INFO   │ ▸ (Module 96 • YourScene   ) Initializing scene 'YourScene' with backend glfw
│DepthFlow├┤1'58.708├┤INFO   │ ▸ (Module 96 • YourScene   ) OpenGL Renderer: NVIDIA GeForce RTX 2060/PCIe/SSE2
│DepthFlow├┤1'58.901├┤INFO   │ ▸ Loading Depth Estimator model (depth-anything/Depth-Anything-V2-base-hf)
│DepthFlow├┤2'00.849├┤INFO   │ ▸ (Module 108 • ShaderObject) Compiling shaders
│DepthFlow├┤2'00.855├┤INFO   │ ▸ (Module 110 • ShaderObject) Compiling shaders
│DepthFlow├┤2'00.867├┤INFO   │ ▸ (Module 96 • YourScene   ) Resized Window to (1920, 3400)

How can I stop it resizing to 3400? Or is that part of the depthflow?
Can I make the output the same size as the input?

Some more info on the Custom.py scene options would be handy too. 
eg: scene.set_upscaler(Realesr())
I assume this is upscaling (duh;_) but what params and how to input for scale, and how does this relate to the resizing above, if at all?

Thanks!

**Comment by Tremeschin** [comment]
Ah, I think I know what's happening. I'm always resetting the base scene's resolution to 1920x1080 (so sizes don't carry on in batch exporting, internal thing)

if you send either width or height to the main function, it'll force this component to be this value, and calculate the other one based on the aspect ratio of the image (or keep it if None)

if you send both width= and height=, it'll prioritize width over height for fitting the other component to the aspect ratio

as the base resolution is 1920x1080, yours input should be an portrait image and it made sure the width=1920, because internally it used the base resolution, calculating height=3400

<hr>

I'll of course write docs about how the scene resolution is calculated on shaderflow (the parent project), but I agree the output video must match the input image (and upscaled if so), this isn't an issue on the web ui as it tracks both components!

will review and improve the example scripts for this and hint some arguments of the realesr class, but you could find them by following the definitions with a python linter :)

**Comment by sonicviz** [comment]
Aok thanks

**Comment by sonicviz** [comment]
Tested it out here: https://youtu.be/Mwve67Ut3Gk?si=ACTtVc2H3XlGM_fJ (unlisted for now, just a demo for another project I'm working with)

**Comment by sonicviz** [comment]
Great thanks!
