### ISSUE TITLE
Enhancement:Integrate Apple's open-source ml-depth-pro depth model

### ISSUE THREAD

**Issue by dedh121224** [BrokenSource/DepthFlow#48]
### 🔘 Request type

Enhancement

### 🔘 Description

Integrate Apple's open-source ml-depth-pro depth model

We propose integrating the ml-depth-pro depth model, recently open-sourced by Apple ([https://github.com/apple/ml-depth-pro](command:_cody.vscode.open?%22https%3A%2F%2Fgithub.com%2Fapple%2Fml-depth-pro%22)), into the project.

**Comment by Tremeschin** [comment]
I saw it yesterday right before sleeping, will take a look today!

A side note: Sharpness isn't great for depthflow as it would cause artifacts on the edges. The most important thing is good relative depth values, we'll see how it goes :eyes:

**Comment by Tremeschin** [comment]
Implemented in https://github.com/BrokenSource/BrokenSource/commit/d898435ebc7e023048bb8458f795f51219a869cd, https://github.com/BrokenSource/DepthFlow/commit/c41694e285b1625deb4722f5d0f4dbc6d8c5c174

![image](https://github.com/user-attachments/assets/782ebf78-ba1f-44fd-a924-919c39acc535)

Honestly, not impressed with the results 😓, maybe I'm doing something wrong but I followed their examples

**Comment by Tremeschin** [comment]
Just saying, they don't provide a PyPI package, so I did a git+ install, it might break at any moment and without notice.

**Comment by adi-panda** [comment]
> I saw it yesterday right before sleeping, will take a look today!
> 
> A side note: Sharpness isn't great for depthflow as it would cause artifacts on the edges. The most important thing is good relative depth values, we'll see how it goes 👀

Just curious, for depth anything v2, would it be better to add a slight blur on the depth map to reduce artifacts on edges?

**Comment by Tremeschin** [comment]
@adi-panda Already doing it [here](https://github.com/BrokenSource/BrokenSource/blob/6e169467a85c361b1eb7b8d4fd185fbe5053f152/Broken/Externals/Depthmap.py#L155)! 🙂

**Comment by adi-panda** [comment]
> @adi-panda Already doing it [here](https://github.com/BrokenSource/BrokenSource/blob/6e169467a85c361b1eb7b8d4fd185fbe5053f152/Broken/Externals/Depthmap.py#L155)! 🙂

Ohh ok nice, amazing stuff!

**Comment by Tremeschin** [comment]
Version v0.8 [released](https://github.com/BrokenSource/DepthFlow/releases/tag/v0.8.0) with DepthPro integration!
