### ISSUE TITLE
Cannot run in the cloud

### ISSUE THREAD

**Issue by O-O1024** [BrokenSource/DepthFlow#50]
### 🔘 Operating system

Linux (Ubuntu-like)

### 🔘 Runtime enviroment

PyPI Wheels (pip, poetry, pdm, rye, etc)

### 🔘 Python version

Python 3.10

### 🔘 GPU Vendor

N/A

### 🔘 Description

[Exception: eglInitialize failed (0x3001)](https://github.com/akatz-ai/ComfyUI-Depthflow-Nodes/issues/8)

**Comment by sonicviz** [comment]
That's a bummer. I was going to test that. 
Isn't this just because " due to not having OpenGL acceleration available"?

It's a shader so you'd need a shader capable backend no?

@Tremeschin What are the exact server requirements needed to run this in the cloud?

**Comment by Tremeschin** [comment]
@sonicviz I've left a pretty length comment in the [linked issue](https://github.com/akatz-ai/ComfyUI-Depthflow-Nodes/issues/8#issuecomment-2402760799), it technically does run on the cloud but highly depends on the provider (inferless and modal seems to be the most easy ones)

**Comment by sonicviz** [comment]
Aok, thanks! Great info.

**Comment by Tremeschin** [comment]
@sonicviz just made some progress in this, see the other issue's [comment](https://github.com/akatz-ai/ComfyUI-Depthflow-Nodes/issues/8#issuecomment-2409098774)

<sup>And subscribe to it if you/others are interested, so I don't spam tag more 🙂</sup>

**Comment by Tremeschin** [comment]
Okei, made it work on runpod with three simple post-setup commands, and it's known to work on modal with the linked script file (after asking their support for moving the workspace to their older runner)

I'll probably try that in a couple more providers (replicate, beam cloud?), feel free to feedback here any progress or reports of it working. Will write a docs page listing each major providers as well!

**Comment by sonicviz** [comment]
Awesome, thanks!

**Comment by sonicviz** [comment]
Do you think it's possible to run this on cloudflare workers via WebGPU?
https://blog.cloudflare.com/webgpu-in-workers/

**Comment by sonicviz** [comment]
No worries, thanks for the insight.

Doing some further research it turns out the cloudflare workers (and similar) are too constrained anyway for this use case. 

eg:
![image](https://github.com/user-attachments/assets/a6ffd620-0c38-4fc2-b019-fa1cdc8caf74)
https://www.remotion.dev/docs/miscellaneous/render-on-edge
