### ISSUE TITLE
Animation styles.

### ISSUE THREAD

**Issue by onlysharma0852** [BrokenSource/DepthFlow#53]
Thanks for adding the circle animation style and other animation style also. But Depthstate animation style is not working. After rendering the video is not moving or i think it is not creating the animation. Also where is the perspective style of animation now? It was present in v0.6 but now its not.

one more thing. How can i change my Rendering processing from CPU to GPU? My system is using the CPU instead for GPU(RTX 3060)

**Comment by Tremeschin** [comment]
> Depthstate animation style is not working

The depthstate doesn't contain any 'animations' indeed, it just sets the starting value of all the parameters that are modulated over time to generate the animation, it's kind of an advanced use / combined with other options

this will probably change in the near future in a upcoming overhaul of the animation system, for better handling how animations should "set" or "add" to the parameters, custom code etc

<br>

> Also where is the perspective style of animation now? It was present in v0.6 but now its not.

hm, which perspective animation? I don't remember it, maybe you're talking about [dolly zoom](https://brokensrc.dev/depthflow/learn/parameters/#dolly) (or videos below) ? could you provide any video of the animation you're looking for or the older version's one 🤔 

<br>

> How can i change my Rendering processing from CPU to GPU

If you're on windows, could [this help](https://brokensrc.dev/about/faq/#q-rendered-videos-are-black)? I know your case isn't black videos, but it's about switching the GPU used, assuming you meant the integrated graphics by _CPU_ :), on linux I never used hybrid systems but it's probably an [optimus](https://wiki.archlinux.org/title/NVIDIA_Optimus)'s duty

**Comment by onlysharma0852** [comment]
WebUI_4_prob3.mp4
<https://drive.google.com/file/d/1hNSMJim4IRLW-6dCR72FvDjzxZS3E46q/view?usp=drive_web>
this animation style.

**Comment by Tremeschin** [comment]
a, this shared link is asking for permission, could you change the visibility or send the video directly on github?

**Comment by onlysharma0852** [comment]
You can watch now.

**Comment by Tremeschin** [comment]
Ah, that's the current default animation called "orbital", took a screenshot and rendering with:

```depthflow input -i ~/mpv-shot0001.jpg orbital main -o ~/video.mp4```


https://github.com/user-attachments/assets/177cb29e-defd-489b-963b-53e3b55a6d9d

**Comment by onlysharma0852** [comment]
Can you add this option in the UI?

**Comment by Tremeschin** [comment]
It's the default injected animation if no other is enabled, and it's already one option in the webui! :)

![image](https://github.com/user-attachments/assets/56ef3b8b-91c1-481e-9430-fd5b81c738e0)

**Comment by onlysharma0852** [comment]
Oh thank you so much. Looks like i was dumb lol.

**Comment by Tremeschin** [comment]
A, no problem! My documentation on it is also kind-of sparse and lacking, I'll rework this as one of the next features and will have proper documentation / examples on the website.

Feel free to ask more stuff about it, just closing as the original issue is fixed

**Comment by onlysharma0852** [comment]
Is it ok if i will promote you on reddit. I also want to other people know
about your project so that they can stop using immersity ai. Is it ok with
if i post it on reddit?

**Comment by Tremeschin** [comment]
Sure! I have taken a minor lead at

https://www.reddit.com/r/StableDiffusion/comments/1dp3o9t/any_leiapix_immersity_ai_alternative_right_now/

and some people have posted creations using (lazy to find the links)

- https://github.com/akatz-ai/ComfyUI-Depthflow-Nodes
- https://civitai.com/models/855031/depthflow-nodes

maybe some other subreddit makes more sense, or just post your creations on r/StableDiffusion itself 👍🏻

**Comment by onlysharma0852** [comment]
Definitely going for it. Thanks

**Comment by onlysharma0852** [comment]
One more thing. Is it also available with A1111

**Comment by Tremeschin** [comment]
> One more thing. Is it also available with A1111

AFAIK no- I could try writing the integration, but I'm not playing with AI gen lately. It also adds more code to maintain when there's "more important things to do". Kind of softly waiting someone to do it like ComfyUI's case 🙂

**Comment by onlysharma0852** [comment]
Well no problem. You are doing great. Keep it up
