### ISSUE TITLE
ImportError: cannot import name 'DepthPro' from 'Broken.Externals.Depthmap' 

### ISSUE THREAD

**Issue by darkon12** [BrokenSource/DepthFlow#55]
### 🔘 Operating system

Linux (Ubuntu-like)

### 🔘 Runtime enviroment

PyPI Wheels (pip, poetry, pdm, rye, etc)

### 🔘 Python version

Python 3.11

### 🔘 GPU Vendor

NVIDIA Desktop

### 🔘 Description

tryin to make it work in colab but I get this error when I run Webui
Any solutions?
thanks

**Comment by Tremeschin** [comment]
It's currently only [available](https://github.com/BrokenSource/DepthFlow/issues/48#issuecomment-2395459480) when running from [source code](https://brokensrc.dev/get/source/) until a v0.8 release (I should have it today or in the next day or two), I integrated it the morning after the current v0.7.1 lol.. _but the question is_, how did you managed to get a newer version of the webui listing depthpro from a pypi install, this code doesn't exist outside the repos 😅

<br>

Colab wise, probably avoid it tbh, see [this documentation](https://raw.githubusercontent.com/BrokenSource/BrokenSource/refs/heads/main/Website/get/docker.md), I know it isn't pretty the raw markdown, but will be on the website alongside the 0.8; tldr, you'll not have opengl GPU acceleration and render speeds will be as bad as 12 seconds per frame, or at least I couldn't [get it to work](https://colab.research.google.com/drive/1C1mmq4GUrhBUeVoX04jAenE3Ex_IDqDB)

**Comment by darkon12** [comment]
I'm looking forward for the 0.8
Colab is my only option since basically I don't have a GPU 
Tried in ComfyUI
https://github.com/akatz-ai/ComfyUI-Depthflow-Nodes
It works pretty well but, yes, deadly slow.
I guess there's a way to have opengl in colab:
https://internet-of-tomohiro.netlify.app/google_colab/vnc.en.html
Maybe you could look into it.
I'll try your notebook later

**Comment by Tremeschin** [comment]
oh yes, I never said it was impossible 🙂, I've also found this [stackoverflow](https://stackoverflow.com/questions/60900067/how-to-run-moderngl-in-colab/60937358#60937358) answer in the past, which is what we need to happen; maybe they only enable this for pro users? I'm only on the free plan

your link is for regular opengl which yes, would require a video server (x11) and VNC for accessing it, but for depthflow we simply need the GPU to show as EGL device for headless rendering (removing all this complexity of a reverse proxy, vgl)

let me know if you make any progress! I should make issue trackers for each provider also hehe

**Comment by Tremeschin** [comment]
Version v0.8 [released](https://github.com/BrokenSource/DepthFlow/releases/tag/v0.8.0) with DepthPro!
