### ISSUE TITLE
How to improve video generation speed?

### ISSUE THREAD

**Issue by C00reNUT** [BrokenSource/DepthFlow#59]
### 🔘 Request type

General feedback

### 🔘 Description

Hello, 
thank you for making this public, I have tried some older versions about half a year ago and the quality in the recent version is much better!

May I ask you - I am trying to improve rendering speed and I have see the comment in Comfy implementation https://github.com/akatz-ai/ComfyUI-Depthflow-Nodes/issues/7 that is saying that is possible to "on RTX 4090 I can complete a 1024x1024 image as a 5 second animation at 30 FPS (so total 150 frames) in 3.5 seconds" - I am trying CLI with 

`xvfb-run depthflow h264 --preset ultrafast input -i image.jpg main -w 640 -h 360 -o ./output_ultrafast.mp4` 

and I am getting around 5min on 3090 card... The speed difference is quite big, considering that 3090 shall be about twice slower as 4090... but I guess most of it will be ffmpeg rendering settings... I have tried different preset flags but it didn't make any difference...

So I thought I would just ask whether there is some quick fix that could speed up the rendering? I haven't go through the code, API and ShaderFlow library yet, I will go through it tomorrow...

btw. great code and very nice documentation, very few single developer projects have this quality!

**Comment by Tremeschin** [comment]
Thanks for the words!

Please avoid `xvfb-run` at all costs, it only supports CPU rendering, you're not using the GPU at all 🙂

I've got a lengthy write-up for a list of cloud providers that are known to work or not at https://brokensrc.dev/get/docker/, as well as running locally instructions and example docker files on the monorepo. Creating the opengl context with egl is a must for servers/true headless rendering linux speeds

I can help you further if you say if it's your own hardware, or some unlisted provider on the docs!

**Comment by Tremeschin** [comment]
try `WINDOW_BACKEND=headless depthflow h264 (...)` 🤔

**Comment by Tremeschin** [comment]
<sup>Heh, claude and gpt.. flashback of spicy conversations wanting to do simple stuff on code</sup>

Awesome!, I'll add this to the examples documentation somewhere as I missed it, in fact, I didn't even start working on shaderflow docs where it should really be 😓, want to rewrite some files before changing focus

Happy to help! feel free to ask me anything in the future as well :), also got some community [groups](https://brokensrc.dev/about/contact/) if you're interested

**Comment by Tremeschin** [comment]
a, I use them all the time, but love and anger are the same point at the opposite side of a circle LOL

I did some work with qwen also, it's indeed one of the best models on the small side for running locally, I have code for ollama on the main repo for some future ideas 👀

one comfyui user did something similar to this infinite parallax repo (which was actually one of the early motivations for the project that was dropped), but I've made good progress yesterday (see the discussion asking to fill in the gaps in the repo), so much potential hehehe

as for sam2, yea, quite heavy models for making image to videos, but they're doing something depthflow could never do: to move objects positions and adding new data with natural motion 😅
