### ISSUE TITLE
Render video from one cli command directly from image and depth map

### ISSUE THREAD

**Issue by C00reNUT** [BrokenSource/DepthFlow#7]
Hello, 
really nice little tool, would it be possible to directly render the video using image and depth map directly from cli?

**Comment by Tremeschin** [comment]
Yes!

- `broken depthflow parallax --image /path/to/background.jpg --depth /path/to/depth.jpg main -r -o ./output.mp4`

or just `-i image.ext -d depth.ext"

You can see other rendering options with `depthflow --help`

I recommend using `-q ultra --saa 1.5` for a better quality, beware it's heavy on GPU

One minor inconvenience is that, for now, the output video doesn't follow the input image's one, gotta input the target  resolution as well `-w 1080 -h 1920` for a 9:16 shorts, for example

**Comment by Tremeschin** [comment]
You can change the animation parameters in the `.update()` method in the file [DepthFlow/DepthFlow.py](https://github.com/BrokenSource/DepthFlow/blob/Master/DepthFlow/DepthFlow.py#L116)

There's a zoom out effect commented in the end of the function, you can change the dolly zoom formula in the top, as well as `self.parallax_height = (number 0 to 1)` for the intensity of the effect

There's not really a presets mechanism yet, for now graphing tools like [Desmos](https://www.desmos.com/calculator) is our best friend on defining the animations

**Comment by Tremeschin** [comment]
Interesting this marigold link, will take a look, potentially being the default one, I like that it's with diffusers

My first guess of the why there was almost no motion is that the output wasn't maybe normalized to 0 and 1 or "wrong" data type being read?

When you open the image, is it black and white or does it have that color palette on their showcase? DepthFlow expects a black and white image

**Comment by Tremeschin** [comment]
> Just one last thing is there any chance to input more than one image/whole folder?

It's not _that_ hard to automate it, I have done it in some proprietary projects, you could, for example, on DepthFlow's `__main__.py` file create your own class

```python
class CustomDepthFlow(DepthFlowScene):
   def pipeline(self):
       ...
   
   # other functions
```

and then automate it with

```python
for image in Path("/folder/of/images").glob("*"):

    # Skip non images
    if not (image.suffix in (".jpg", ".png")):
        continue
     
    # Create scene and export to video
    depthflow = CustomDepthFlow()
    depthflow.parallax(image=image)
    width, height = PIL.Image.open(image).size
    depthflow.main(
        ssaa=1.25,
        width=width,
        height=height,
        quality="ultra",
        output=image.with_suffix(".mp4"),
    )
```

**Comment by Tremeschin** [comment]
> 12GB for one 1280x720 image.

Ouch 😅, maybe half precision could help, thanks for letting me know of its existence btw

**Comment by Tremeschin** [comment]
> does it use CUDA by default when I installed the repo using broken depthflow poe cuda?

Yes, whenever CUDA is available as seen in [this line](https://github.com/BrokenSource/DepthFlow/blob/Master/DepthFlow/Modules/DepthFlowMDE.py#L20) it gets used automatically

First time running `broken depthflow` it defaults to CPU mode (I wonder if I should make CUDA the default one?), then running `broken depthflow poe cuda` once uninstalls PyTorch CPU and installs the CUDA on the virtual environment (hacky way, torch packaging is really painful, same package name, multiple "versions")

**Comment by Tremeschin** [comment]
> > > 12GB for one 1280x720 image.
> > 
> > 
> > Ouch 😅, maybe half precision could help, thanks for letting me know of its existence btw
> 
> Sure, another recent one that is far superior according to metrics is https://zhyever.github.io/patchfusion/ but I haven't tried it

Just tried it, and LOL here goes 11 GB of my 3060 for that default 4k mountains image and about a minute to process, nearly running out of memory, depth results follows

![fe0a6b3435d86d8c295e1d95a76145ff](https://github.com/BrokenSource/DepthFlow/assets/29046864/56e2fb68-a1b6-481d-b6df-942d27bcc5da)

I don't know why it's grainy, I used full precision on torch.. probably image too big? who knows heh

Given the VRAM usage and time I think zoedepth is the most practical one to be the default, will look forward having options for alternatives depth estimations though

**Comment by Tremeschin** [comment]
> Great, well I prefer standard conda env file - install through yaml file, than using poetry for CUDA based projects... all the handling of torch cuda dependencies is much easier...

Thanks for the feedback about getting the dependencies !

I don't know enough of conda to implement or know its benefits tbh, I remember I had more luck with it on Windows long ago (early Python 3 era, mostly NumPy), nowadays stuff just worked, and binaries exists on PyPI for most of blob packages

If there's demand for it or it proves useful enough I can try integrating it, beware I'll need path dependencies for the monorepo, don't know if it's supported on the yaml spec file

**Comment by Tremeschin** [comment]
Just talking to myself of what I said earlier,

> I recommend using `-q ultra --ssaa 1.5` for a better quality, beware it's heavy on GPU

I hope with the new texture class rewrite I'll be able to do multi-passes and store previous computation of displacements of the parallax effect to be reused, potentially saving a lot of GPU computational power!

**Comment by Tremeschin** [comment]
Unlikely it is poetry messing with the files, I commented these lines on `DepthFlow.py` and get no movement at all on the builtin realtime window

If you're on the custom class, you should override `update(self)` (I wrote the wrong method on an earlier comment)

My best guess is the later is your case and probably the default implementation `update` was still there due inheritance, but can also be the wrong file path you're editing if you cloned twice (it happens sometime)

Yours `__main__.py` should look something like:

```python
from DepthFlow import *

class CustomDepthFlow(DepthFlowScene):
    def update(self):
        # Dolly zoom example
        self.parallax_dolly = 10 * math.atan(self.time)
        ...

def main():
    depthflow = CustomDepthFlow()

    # The automation thing if run with BATCH=1 depthflow
    if os.environ.get("BATCH", "0") == "1":
        for image in Path("/folder/of/images").glob("*"):
            ...
        return

    # Realtime window or CLI
    with BrokenProfiler("DEPTHFLOW"):
        DEPTHFLOW.welcome()
        depthflow.cli(sys.argv[1:])

if __name__ == "__main__":
    main()
```

> 1280x768 image as input I see only 76MB in 'watch nvidia-smi' so it's not particullary GPU heavy

Yes, not heavy on VRAM, but it really hits on the pixel shaders circuitry (""rasterization""), when I'm rendering lots of 1440p or 4k images in parallel with some super sampling and really low displacement steps (high quality), the textures accesses per second easily hit the trillions. Somehow current shader is still enough to run at 4k60 on the "ultra" quality in real time on my RTX 3060 and 8k30 (not that the later is practical lol)

**Comment by Tremeschin** [comment]
It's not documented yet and a bit technical, yet to make some form of infographic, but as you'll be dealing with dolly zoom and the parameters, there's `dolly`, `isometric` and `zoom` parameters

- **Zoom** multiplies the screen projection plane by this amount

- **Dolly** is a distance in units (center screen is 0, top screen is 1, bottom -1) of how far "back" from the screen the ray projection starts of the camera (range 0 to infty)

- **Isometric** is a number that controls the size of the projection plane of the ray origin relative to the "screen" plane, which have sides equal to `fov*isometric` as the screen one is just `fov`, a number equal to 1 is equal to `dolly=VeryBig`
